package com.single.flowlayout;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by xiangcheng on 17/4/13.
 */

public class DataConfig {

    public static List<ShowItem> getItems() {
        List<ShowItem> showItems = new ArrayList<>();
        showItems.add(new ShowItem("1.C"));
        showItems.add(new ShowItem("2.Java"));
        showItems.add(new ShowItem("3.Objective-C"));
        showItems.add(new ShowItem("4.C++"));
        showItems.add(new ShowItem("5.PHP"));
        showItems.add(new ShowItem("6.C#"));
        showItems.add(new ShowItem("7.(Visual) Basic"));
        showItems.add(new ShowItem("8.Python"));
        showItems.add(new ShowItem("9.Perl"));
        showItems.add(new ShowItem("10.JavaScript"));
//        showItems.add(new ShowItem("11.Ruby"));
//        showItems.add(new ShowItem("12.Visual Basic .NET"));
//        showItems.add(new ShowItem("13.Transact-SQL"));
//        showItems.add(new ShowItem("14.Lisp"));
//        showItems.add(new ShowItem("15.Pascal"));
//        showItems.add(new ShowItem("16.Bash"));
//        showItems.add(new ShowItem("17.PL/SQL"));
//        showItems.add(new ShowItem("18.Delphi/Object Pascal"));
//        showItems.add(new ShowItem("19.Ada"));
//        showItems.add(new ShowItem("20.MATLAB"));
//        showItems.add(new ShowItem("1.C"));
//        showItems.add(new ShowItem("2.Java"));
//        showItems.add(new ShowItem("3.Objective-C"));
//        showItems.add(new ShowItem("4.C++"));
//        showItems.add(new ShowItem("5.PHP"));
//        showItems.add(new ShowItem("6.C#"));
//        showItems.add(new ShowItem("7.(Visual) Basic"));
//        showItems.add(new ShowItem("8.Python"));
//        showItems.add(new ShowItem("9.Perl"));
//        showItems.add(new ShowItem("10.JavaScript"));
//        showItems.add(new ShowItem("11.Ruby"));
//        showItems.add(new ShowItem("12.Visual Basic .NET"));
//        showItems.add(new ShowItem("13.Transact-SQL"));
//        showItems.add(new ShowItem("14.Lisp"));
//        showItems.add(new ShowItem("15.Pascal"));
//        showItems.add(new ShowItem("16.Bash"));
//        showItems.add(new ShowItem("17.PL/SQL"));
//        showItems.add(new ShowItem("18.Delphi/Object Pascal"));
//        showItems.add(new ShowItem("19.Ada"));
//        showItems.add(new ShowItem("20.MATLAB"));
//        showItems.add(new ShowItem("1.C"));
//        showItems.add(new ShowItem("2.Java"));
//        showItems.add(new ShowItem("3.Objective-C"));
//        showItems.add(new ShowItem("4.C++"));
//        showItems.add(new ShowItem("5.PHP"));
//        showItems.add(new ShowItem("6.C#"));
//        showItems.add(new ShowItem("7.(Visual) Basic"));
//        showItems.add(new ShowItem("8.Python"));
//        showItems.add(new ShowItem("9.Perl"));
//        showItems.add(new ShowItem("10.JavaScript"));
//        showItems.add(new ShowItem("11.Ruby"));
//        showItems.add(new ShowItem("12.Visual Basic .NET"));
//        showItems.add(new ShowItem("13.Transact-SQL"));
//        showItems.add(new ShowItem("14.Lisp"));
//        showItems.add(new ShowItem("15.Pascal"));
//        showItems.add(new ShowItem("16.Bash"));
//        showItems.add(new ShowItem("17.PL/SQL"));
//        showItems.add(new ShowItem("18.Delphi/Object Pascal"));
//        showItems.add(new ShowItem("19.Ada"));
//        showItems.add(new ShowItem("20.MATLAB"));

        return showItems;
    }

    public static List<ShowItem> getDiffItem() {
        List<ShowItem> showItems2 = new ArrayList<>();
        showItems2.add(new ShowItem("宋江"));
        showItems2.add(new ShowItem("卢俊义"));
        showItems2.add(new ShowItem("吴用"));
        showItems2.add(new ShowItem("公孙胜"));
        showItems2.add(new ShowItem("关胜"));
        showItems2.add(new ShowItem("林冲"));
        showItems2.add(new ShowItem("秦明"));
        showItems2.add(new ShowItem("呼延灼"));
        showItems2.add(new ShowItem("花荣"));
        showItems2.add(new ShowItem("柴进"));
        showItems2.add(new ShowItem("李应"));
        showItems2.add(new ShowItem("朱仝"));
        showItems2.add(new ShowItem("鲁智深"));
        showItems2.add(new ShowItem("武松"));
        showItems2.add(new ShowItem("董平"));
        showItems2.add(new ShowItem("张清"));
        showItems2.add(new ShowItem("杨志"));
        showItems2.add(new ShowItem("徐宁"));
        showItems2.add(new ShowItem("索超"));
        showItems2.add(new ShowItem("戴宗"));
        showItems2.add(new ShowItem("刘唐"));
        showItems2.add(new ShowItem("李逵"));
        showItems2.add(new ShowItem("史进"));
        showItems2.add(new ShowItem("穆弘"));
        showItems2.add(new ShowItem("雷横"));
        showItems2.add(new ShowItem("李俊"));
        showItems2.add(new ShowItem("阮小二"));
        showItems2.add(new ShowItem("张横"));
        showItems2.add(new ShowItem("阮小五"));
        showItems2.add(new ShowItem("张顺"));
        showItems2.add(new ShowItem("阮小七"));
        showItems2.add(new ShowItem("杨雄"));
        showItems2.add(new ShowItem("石秀"));
        showItems2.add(new ShowItem("解珍"));
        showItems2.add(new ShowItem("解宝"));
        showItems2.add(new ShowItem("燕青"));
        showItems2.add(new ShowItem("宋江"));
        showItems2.add(new ShowItem("卢俊义"));
        showItems2.add(new ShowItem("吴用"));
        showItems2.add(new ShowItem("公孙胜"));
        showItems2.add(new ShowItem("关胜"));
        showItems2.add(new ShowItem("林冲"));
        showItems2.add(new ShowItem("秦明"));
        showItems2.add(new ShowItem("呼延灼"));
        showItems2.add(new ShowItem("花荣"));
        showItems2.add(new ShowItem("柴进"));
        showItems2.add(new ShowItem("李应"));
        showItems2.add(new ShowItem("朱仝"));
        showItems2.add(new ShowItem("鲁智深"));
        showItems2.add(new ShowItem("武松"));
        showItems2.add(new ShowItem("董平"));
        showItems2.add(new ShowItem("张清"));
        showItems2.add(new ShowItem("杨志"));
        showItems2.add(new ShowItem("徐宁"));
        return showItems2;
    }

    public static List<ShowItem> getViewPagerItem() {
        List<ShowItem> showItems = new ArrayList<>();
        showItems.add(new ShowItem("1.C"));
        showItems.add(new ShowItem("2.Java"));
        showItems.add(new ShowItem("3.Objective-C"));
        showItems.add(new ShowItem("4.C++"));
        showItems.add(new ShowItem("5.PHP"));
        showItems.add(new ShowItem("6.C#"));
        showItems.add(new ShowItem("7.(Visual) Basic"));
        showItems.add(new ShowItem("8.Python"));
        showItems.add(new ShowItem("9.Perl"));
        showItems.add(new ShowItem("10.JavaScript"));
        showItems.add(new ShowItem("11.Ruby"));
        showItems.add(new ShowItem("12.Visual Basic .NET"));
        showItems.add(new ShowItem("13.Transact-SQL"));
        showItems.add(new ShowItem("14.Lisp"));
        showItems.add(new ShowItem("15.Pascal"));
        showItems.add(new ShowItem("16.Bash"));
        showItems.add(new ShowItem("17.PL/SQL"));
        showItems.add(new ShowItem("18.Delphi/Object Pascal"));
        showItems.add(new ShowItem("19.Ada"));
        showItems.add(new ShowItem("20.MATLAB"));
        showItems.add(new ShowItem("1.C"));
        showItems.add(new ShowItem("2.Java"));
        showItems.add(new ShowItem("3.Objective-C"));
        showItems.add(new ShowItem("4.C++"));
        showItems.add(new ShowItem("5.PHP"));
        showItems.add(new ShowItem("6.C#"));
        showItems.add(new ShowItem("7.(Visual) Basic"));
        showItems.add(new ShowItem("8.Python"));
        showItems.add(new ShowItem("9.Perl"));
        showItems.add(new ShowItem("10.JavaScript"));
        showItems.add(new ShowItem("11.Ruby"));
        showItems.add(new ShowItem("12.Visual Basic .NET"));
        showItems.add(new ShowItem("13.Transact-SQL"));
        showItems.add(new ShowItem("14.Lisp"));
        showItems.add(new ShowItem("15.Pascal"));
        showItems.add(new ShowItem("16.Bash"));
        showItems.add(new ShowItem("17.PL/SQL"));
        showItems.add(new ShowItem("18.Delphi/Object Pascal"));
        showItems.add(new ShowItem("19.Ada"));
        showItems.add(new ShowItem("20.MATLAB"));
        showItems.add(new ShowItem("1.C"));
        showItems.add(new ShowItem("2.Java"));
        showItems.add(new ShowItem("3.Objective-C"));
        showItems.add(new ShowItem("4.C++"));
        showItems.add(new ShowItem("5.PHP"));
        showItems.add(new ShowItem("6.C#"));
        showItems.add(new ShowItem("7.(Visual) Basic"));
        showItems.add(new ShowItem("8.Python"));
        showItems.add(new ShowItem("9.Perl"));
        showItems.add(new ShowItem("10.JavaScript"));
        showItems.add(new ShowItem("11.Ruby"));
        showItems.add(new ShowItem("12.Visual Basic .NET"));
        showItems.add(new ShowItem("13.Transact-SQL"));
        showItems.add(new ShowItem("14.Lisp"));
        showItems.add(new ShowItem("15.Pascal"));
        showItems.add(new ShowItem("16.Bash"));
        showItems.add(new ShowItem("17.PL/SQL"));
        showItems.add(new ShowItem("18.Delphi/Object Pascal"));
        showItems.add(new ShowItem("19.Ada"));
        showItems.add(new ShowItem("20.MATLAB"));

        return showItems;
    }
}
